import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Staatliches,
  Rubik,
} from "next/font/google";
import "./globals.css";
import "./styles.css";
import { cn } from "@/lib/utils";
import NavBar from "./components/navbar";
import Footer from "./components/footer";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-sans" });
const staatliches = Staatliches({ weight: "400", variable: "--font-heading" });
const rubik = Rubik({ weight: "500", variable: "--font-serif" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Popshack PH",
  description: "Generated by CSSWENG Group 5",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        montserrat.variable,
        staatliches.variable,
        rubik.variable,
      )}
    >
      <body className="min-h-screen flex flex-col">
        <NavBar />
        <main className="flex-1">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
